name: Test for sample-container-todo-app-java-maven for staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:
    secrets:
      THUNDRA_STAGING_APIKEY:
        required: true
      THUNDRA_REGISTRY:
        required: true
      THUNDRA_REGISTRY_AUTH:
        required: true
env:
  FORESIGHT_UPLOADER_SIGNER_URL: https://upload.thundra.us
  WORKFLOW_TELEMETRY_BASE_URL: https://foresight.service.thundra.us
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 8, 11, 16 ]
    name: Run Tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Foresight Workflow Kit Action
        uses: runforesight/foresight-workflow-kit-action@v1
        with:
          api_key: ${{ secrets.THUNDRA_STAGING_APIKEY }}
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.jdk }}
          distribution: 'adopt'
          cache: 'maven'
      - name: Run Tests with Maven
        run: ./mvnw clean test
      - name: Thundra Registry
        run: |
          npm config set registry ${{ secrets.THUNDRA_REGISTRY }}
          npm config set _auth ${{ secrets.THUNDRA_REGISTRY_AUTH }}
      - name: Foresight Test Kit Action
        uses: runforesight/foresight-test-kit-action@v1
        with:
          api_key: ${{ secrets.THUNDRA_STAGING_APIKEY }}
          test_framework: junit
          test_path: target/surefire-reports/**
          coverage_format: jacoco/xml
          coverage_path: target/site/jacoco/*.xml
          cli_version: 123.321.5
